# Generated by Django 4.1.13 on 2024-06-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('mobile_phone', models.CharField(blank=True, max_length=9, null=True)),
                ('health_number', models.CharField(blank=True, max_length=9, null=True)),
                ('taxpayer_number', models.CharField(blank=True, max_length=9, null=True)),
                ('type_user', models.CharField(choices=[('profissional', 'Profissional'), ('paciente', 'Paciente'), ('admin', 'Admin')], default='profissional', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, related_name='users', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
