# Generated by Django 4.1.13 on 2024-06-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0002_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_phone',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sns_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='taxpayer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
