# Generated by Django 4.1.13 on 2024-06-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0003_customuser_mobile_phone_customuser_sns_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sns_number',
            new_name='health_number',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='taxpayer',
            new_name='taxpayer_number',
        ),
    ]
