# Generated by Django 4.1.13 on 2024-06-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0004_rename_sns_number_customuser_health_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(default='profissional', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='health_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='taxpayer_number',
            field=models.IntegerField(default=0),
        ),
    ]
