# Generated by Django 4.1.13 on 2024-06-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0005_customuser_type_user_alter_customuser_health_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('profissional', 'Profissional'), ('paciente', 'Paciente')], default='profissional', max_length=255),
        ),
    ]
