# Generated by Django 4.1.13 on 2024-06-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0008_alter_customuser_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='health_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_phone',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='taxpayer_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
