# Generated by Django 4.1.13 on 2024-06-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0009_alter_customuser_health_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='health_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='taxpayer_number',
            field=models.IntegerField(default=0),
        ),
    ]
