# Generated by Django 4.1.13 on 2024-06-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0011_alter_customuser_health_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='health_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
