# Generated by Django 4.1.13 on 2024-06-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0012_alter_customuser_health_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='taxpayer_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
