# Generated by Django 4.1.13 on 2024-06-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0013_alter_customuser_taxpayer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='health_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='taxpayer_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
